### ISSUE TITLE
little fix for 2019-04-03-system-f-in-coq.md

### ISSUE THREAD

**Issue by p-alik** [Lysxia/coq-mtl#2]
Sorry for opening an issue here, but there is no ability to do that in https://bitbucket.org/lyxia/blog.poisson.chat

You have to add `https://` in front of `github`-link behind  `my other project` in https://bitbucket.org/lyxia/blog.poisson.chat/src/master/posts/2019-04-03-system-f-in-coq.md

```diff
diff  2019-04-03-system-f-in-coq.md{,~} 
153c153
< endeavor was sparked by [my other project](github.com/Lysxia/coq-mtl) of
---
> endeavor was sparked by [my other project](https://github.com/Lysxia/coq-mtl) of
```

**Comment by Lysxia** [comment]
Oh! Good catch! Thanks a lot :)

I also opened the issue tracker on bitbucket from now on.
